<?php
/**
 * BuyingDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MYOB AccountRight
 *
 * MYOB AccountRight API file
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyobAPI\MyobPHP;

use PHPUnit\Framework\TestCase;

/**
 * BuyingDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description BuyingDetails
 * @package     MyobAPI\MyobPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BuyingDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BuyingDetails"
     */
    public function testBuyingDetails()
    {
    }

    /**
     * Test attribute "purchase_layout"
     */
    public function testPropertyPurchaseLayout()
    {
    }

    /**
     * Test attribute "printed_form"
     */
    public function testPropertyPrintedForm()
    {
    }

    /**
     * Test attribute "purchase_order_delivery"
     */
    public function testPropertyPurchaseOrderDelivery()
    {
    }

    /**
     * Test attribute "expense_account"
     */
    public function testPropertyExpenseAccount()
    {
    }

    /**
     * Test attribute "payment_memo"
     */
    public function testPropertyPaymentMemo()
    {
    }

    /**
     * Test attribute "purchase_comment"
     */
    public function testPropertyPurchaseComment()
    {
    }

    /**
     * Test attribute "supplier_billing_rate"
     */
    public function testPropertySupplierBillingRate()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "is_reportable"
     */
    public function testPropertyIsReportable()
    {
    }

    /**
     * Test attribute "cost_per_hour"
     */
    public function testPropertyCostPerHour()
    {
    }

    /**
     * Test attribute "credit"
     */
    public function testPropertyCredit()
    {
    }

    /**
     * Test attribute "abn"
     */
    public function testPropertyAbn()
    {
    }

    /**
     * Test attribute "abn_branch"
     */
    public function testPropertyAbnBranch()
    {
    }

    /**
     * Test attribute "tax_id_number"
     */
    public function testPropertyTaxIdNumber()
    {
    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {
    }

    /**
     * Test attribute "freight_tax_code"
     */
    public function testPropertyFreightTaxCode()
    {
    }

    /**
     * Test attribute "use_supplier_tax_code"
     */
    public function testPropertyUseSupplierTaxCode()
    {
    }

    /**
     * Test attribute "terms"
     */
    public function testPropertyTerms()
    {
    }

    /**
     * Test attribute "payment_details"
     */
    public function testPropertyPaymentDetails()
    {
    }
}
