<?php
/**
 * DebitRefundTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MYOB AccountRight
 *
 * MYOB AccountRight API file
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyobAPI\MyobPHP;

use PHPUnit\Framework\TestCase;

/**
 * DebitRefundTest Class Doc Comment
 *
 * @category    Class
 * @description DebitRefund
 * @package     MyobAPI\MyobPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DebitRefundTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DebitRefund"
     */
    public function testDebitRefund()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "deposit_to"
     */
    public function testPropertyDepositTo()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "bill"
     */
    public function testPropertyBill()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "foreign_currency"
     */
    public function testPropertyForeignCurrency()
    {
    }

    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {
    }

    /**
     * Test attribute "row_version"
     */
    public function testPropertyRowVersion()
    {
    }
}
