<?php
/**
 * EditSupplierRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MYOB AccountRight
 *
 * MYOB AccountRight API file
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyobAPI\MyobPHP;

use PHPUnit\Framework\TestCase;

/**
 * EditSupplierRequestTest Class Doc Comment
 *
 * @category    Class
 * @description EditSupplierRequest
 * @package     MyobAPI\MyobPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EditSupplierRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EditSupplierRequest"
     */
    public function testEditSupplierRequest()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "is_individual"
     */
    public function testPropertyIsIndividual()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "display_id"
     */
    public function testPropertyDisplayId()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "identifiers"
     */
    public function testPropertyIdentifiers()
    {
    }

    /**
     * Test attribute "custom_list1"
     */
    public function testPropertyCustomList1()
    {
    }

    /**
     * Test attribute "custom_list2"
     */
    public function testPropertyCustomList2()
    {
    }

    /**
     * Test attribute "custom_list3"
     */
    public function testPropertyCustomList3()
    {
    }

    /**
     * Test attribute "custom_field1"
     */
    public function testPropertyCustomField1()
    {
    }

    /**
     * Test attribute "custom_field2"
     */
    public function testPropertyCustomField2()
    {
    }

    /**
     * Test attribute "custom_field3"
     */
    public function testPropertyCustomField3()
    {
    }

    /**
     * Test attribute "buying_details"
     */
    public function testPropertyBuyingDetails()
    {
    }

    /**
     * Test attribute "payment_details"
     */
    public function testPropertyPaymentDetails()
    {
    }
}
