<?php
/**
 * EditItemBillTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MYOB AccountRight
 *
 * MYOB AccountRight API file
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyobAPI\MyobPHP;

use PHPUnit\Framework\TestCase;

/**
 * EditItemBillTest Class Doc Comment
 *
 * @category    Class
 * @description EditItemBill
 * @package     MyobAPI\MyobPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EditItemBillTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EditItemBill"
     */
    public function testEditItemBill()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "supplier_invoice_number"
     */
    public function testPropertySupplierInvoiceNumber()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "ship_to_address"
     */
    public function testPropertyShipToAddress()
    {
    }

    /**
     * Test attribute "terms"
     */
    public function testPropertyTerms()
    {
    }

    /**
     * Test attribute "is_tax_inclusive"
     */
    public function testPropertyIsTaxInclusive()
    {
    }

    /**
     * Test attribute "is_reportable"
     */
    public function testPropertyIsReportable()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "subtotal_foreign"
     */
    public function testPropertySubtotalForeign()
    {
    }

    /**
     * Test attribute "freight"
     */
    public function testPropertyFreight()
    {
    }

    /**
     * Test attribute "freight_tax_code"
     */
    public function testPropertyFreightTaxCode()
    {
    }

    /**
     * Test attribute "total_tax"
     */
    public function testPropertyTotalTax()
    {
    }

    /**
     * Test attribute "total_tax_foreign"
     */
    public function testPropertyTotalTaxForeign()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "total_amount_foreign"
     */
    public function testPropertyTotalAmountForeign()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "promised_date"
     */
    public function testPropertyPromisedDate()
    {
    }

    /**
     * Test attribute "journal_memo"
     */
    public function testPropertyJournalMemo()
    {
    }

    /**
     * Test attribute "bill_delivery_status"
     */
    public function testPropertyBillDeliveryStatus()
    {
    }

    /**
     * Test attribute "applied_to_date"
     */
    public function testPropertyAppliedToDate()
    {
    }

    /**
     * Test attribute "applied_to_date_foreign"
     */
    public function testPropertyAppliedToDateForeign()
    {
    }

    /**
     * Test attribute "balance_due_amount"
     */
    public function testPropertyBalanceDueAmount()
    {
    }

    /**
     * Test attribute "balance_due_amount_foreign"
     */
    public function testPropertyBalanceDueAmountForeign()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "last_payment_date"
     */
    public function testPropertyLastPaymentDate()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "foreign_currency"
     */
    public function testPropertyForeignCurrency()
    {
    }

    /**
     * Test attribute "currency_exchange_rate"
     */
    public function testPropertyCurrencyExchangeRate()
    {
    }

    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {
    }

    /**
     * Test attribute "row_version"
     */
    public function testPropertyRowVersion()
    {
    }
}
