<?php
/**
 * ItemBillTermsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MYOB AccountRight
 *
 * MYOB AccountRight API file
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MyobAPI\MyobPHP;

use PHPUnit\Framework\TestCase;

/**
 * ItemBillTermsTest Class Doc Comment
 *
 * @category    Class
 * @description ItemBillTerms
 * @package     MyobAPI\MyobPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ItemBillTermsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemBillTerms"
     */
    public function testItemBillTerms()
    {
    }

    /**
     * Test attribute "payment_is_due"
     */
    public function testPropertyPaymentIsDue()
    {
    }

    /**
     * Test attribute "discount_date"
     */
    public function testPropertyDiscountDate()
    {
    }

    /**
     * Test attribute "balance_due_date"
     */
    public function testPropertyBalanceDueDate()
    {
    }

    /**
     * Test attribute "discount_for_early_payment"
     */
    public function testPropertyDiscountForEarlyPayment()
    {
    }

    /**
     * Test attribute "monthly_charge_for_late_payment"
     */
    public function testPropertyMonthlyChargeForLatePayment()
    {
    }

    /**
     * Test attribute "discount_expiry_date"
     */
    public function testPropertyDiscountExpiryDate()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "discount_foreign"
     */
    public function testPropertyDiscountForeign()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }
}
