<?php
/**
 * SupplierApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MYOB AccountRight
 *
 * MYOB AccountRight API file
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MyobAPI\MyobPHP;

use \MyobAPI\MyobPHP\Configuration;
use \MyobAPI\MyobPHP\ApiException;
use \MyobAPI\MyobPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SupplierApiTest Class Doc Comment
 *
 * @category Class
 * @package  MyobAPI\MyobPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupplierApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSupplier
     *
     * Create a new supplier.
     *
     */
    public function testCreateSupplier()
    {
    }

    /**
     * Test case for deleteSupplier
     *
     * Delete a supplier.
     *
     */
    public function testDeleteSupplier()
    {
    }

    /**
     * Test case for editSupplier
     *
     * Edit a supplier.
     *
     */
    public function testEditSupplier()
    {
    }

    /**
     * Test case for getSuppliers
     *
     * Fetch a list of all Suppliers.
     *
     */
    public function testGetSuppliers()
    {
    }
}
